# Generated by Django 4.1.7 on 2023-03-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='breed',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
